manifest:
  self:
    path: modules/importunity

  projects:
    - name: unity
    description: Unity Test framework
    url: https://github.com/ThrowTheSwitch/Unity.git
    revision: v2.6.0
    path: modules/unity