/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifdef TEST_UNITY_FLOATS

#include "run_test_unity.h"
#include "test_unity_floats.c"

void run_test_unity_floats(void)
{
    RUN_TEST(testFloatsWithinDelta);
    RUN_TEST(testFloatsNotWithinDelta);
    RUN_TEST(testFloatsEqual);
    RUN_TEST(testFloatsNotEqual);
    RUN_TEST(testFloatsNotEqualNegative1);
    RUN_TEST(testFloatsNotEqualNegative2);
    RUN_TEST(testFloatsNotEqualActualNaN);
    RUN_TEST(testFloatsNotEqualExpectedNaN);
    RUN_TEST(testFloatsEqualBothNaN);
    RUN_TEST(testFloatsNotEqualInfNaN);
    RUN_TEST(testFloatsNotEqualNaNInf);
    RUN_TEST(testFloatsNotEqualActualInf);
    RUN_TEST(testFloatsNotEqualExpectedInf);
    RUN_TEST(testFloatsEqualBothInf);
    RUN_TEST(testFloatsNotEqualPlusMinusInf);
    RUN_TEST(testFloatsGreaterThan);
    RUN_TEST(testFloatsGreaterThanInf);
    RUN_TEST(testFloatsNotGreaterThan);
    RUN_TEST(testFloatsNotGreaterThanNanActual);
    RUN_TEST(testFloatsNotGreaterThanNanThreshold);
    RUN_TEST(testFloatsNotGreaterThanNanBoth);
    RUN_TEST(testFloatsNotGreaterThanInfActual);
    RUN_TEST(testFloatsNotGreaterThanNegInf);
    RUN_TEST(testFloatsNotGreaterThanBothInf);
    RUN_TEST(testFloatsNotGreaterThanBothNegInf);
    RUN_TEST(testFloatsGreaterOrEqual);
    RUN_TEST(testFloatsGreaterOrEqualInf);
    RUN_TEST(testFloatsNotGreaterOrEqual);
    RUN_TEST(testFloatsNotGreaterOrEqualNanActual);
    RUN_TEST(testFloatsNotGreaterOrEqualNanThreshold);
    RUN_TEST(testFloatsGreaterOrEqualNanBoth);
    RUN_TEST(testFloatsNotGreaterOrEqualInfActual);
    RUN_TEST(testFloatsNotGreaterOrEqualNegInf);
    RUN_TEST(testFloatsGreaterOrEqualBothInf);
    RUN_TEST(testFloatsGreaterOrEqualBothNegInf);
    RUN_TEST(testFloatsLessThan);
    RUN_TEST(testFloatsLessThanInf);
    RUN_TEST(testFloatsNotLessThan);
    RUN_TEST(testFloatsNotLessThanNanActual);
    RUN_TEST(testFloatsNotLessThanNanThreshold);
    RUN_TEST(testFloatsNotLessThanNanBoth);
    RUN_TEST(testFloatsNotLessThanInf);
    RUN_TEST(testFloatsNotLessThanNegInf);
    RUN_TEST(testFloatsNotLessThanBothInf);
    RUN_TEST(testFloatsNotLessThanBothNegInf);
    RUN_TEST(testFloatsLessOrEqual);
    RUN_TEST(testFloatsLessOrEqualInf);
    RUN_TEST(testFloatsNotLessOrEqual);
    RUN_TEST(testFloatsNotLessOrEqualNanActual);
    RUN_TEST(testFloatsNotLessOrEqualNanThreshold);
    RUN_TEST(testFloatsLessOrEqualNanBoth);
    RUN_TEST(testFloatsNotLessOrEqualInf);
    RUN_TEST(testFloatsNotLessOrEqualNegInf);
    RUN_TEST(testFloatsLessOrEqualBothInf);
    RUN_TEST(testFloatsLessOrEqualBothNegInf);
    RUN_TEST(testFloatIsPosInf1);
    RUN_TEST(testFloatIsPosInf2);
    RUN_TEST(testFloatIsNegInf1);
    RUN_TEST(testFloatIsNegInf2);
    RUN_TEST(testFloatIsNotPosInf1);
    RUN_TEST(testFloatIsNotPosInf2);
    RUN_TEST(testFloatIsNotNegInf);
    RUN_TEST(testFloatIsNan1);
    RUN_TEST(testFloatIsNan2);
    RUN_TEST(testFloatIsNotNan1);
    RUN_TEST(testFloatIsNotNan2);
    RUN_TEST(testFloatInfIsNotNan);
    RUN_TEST(testFloatNanIsNotInf);
    RUN_TEST(testFloatIsDeterminate1);
    RUN_TEST(testFloatIsDeterminate2);
    RUN_TEST(testFloatIsNotDeterminate1);
    RUN_TEST(testFloatIsNotDeterminate2);
    RUN_TEST(testFloatTraitFailsOnInvalidTrait);
    RUN_TEST(testEqualFloatArrays);
    RUN_TEST(testNotEqualFloatArraysExpectedNull);
    RUN_TEST(testNotEqualFloatArraysActualNull);
    RUN_TEST(testNotEqualFloatArrays1);
    RUN_TEST(testNotEqualFloatArrays2);
    RUN_TEST(testNotEqualFloatArrays3);
    RUN_TEST(testNotEqualFloatArraysNegative1);
    RUN_TEST(testNotEqualFloatArraysNegative2);
    RUN_TEST(testNotEqualFloatArraysNegative3);
    RUN_TEST(testEqualFloatArraysNaN);
    RUN_TEST(testEqualFloatArraysInf);
    RUN_TEST(testNotEqualFloatArraysLengthZero);
    RUN_TEST(testFloatArraysWithin);
    RUN_TEST(testFloatArraysWithinUnusualDelta);
    RUN_TEST(testEqualFloatEachEqual);
    RUN_TEST(testNotEqualFloatEachEqualActualNull);
    RUN_TEST(testNotEqualFloatEachEqual1);
    RUN_TEST(testNotEqualFloatEachEqual2);
    RUN_TEST(testNotEqualFloatEachEqual3);
    RUN_TEST(testNotEqualFloatEachEqualNegative1);
    RUN_TEST(testNotEqualFloatEachEqualNegative2);
    RUN_TEST(testNotEqualFloatEachEqualNegative3);
    RUN_TEST(testEqualFloatEachEqualNaN);
    RUN_TEST(testEqualFloatEachEqualInf);
    RUN_TEST(testNotEqualFloatEachEqualLengthZero);
    RUN_TEST(testFloatPrinting);
    RUN_TEST(testFloatPrintingRoundTiesToEven);
    RUN_TEST(testFloatPrintingInfinityAndNaN);
    RUN_TEST(testFloatPrintingRandomSamples);
}

#endif